version: 2
sources:
  - name: raw_data
    schema: '{{ var ("source_dataset_name") }}'
    tables:
      - name: _dlt_loads
      - name: products
      - name: orders
      - name: customers
      - name: customers__addresses
      - name: orders__payment_gateway_names
      - name: orders__tax_lines
      - name: orders__fulfillments
      - name: orders__fulfillments__line_items
      - name: orders__fulfillments__line_items__tax_lines
      - name: orders__fulfillments__receipt__gift_cards
      - name: orders__line_items
      - name: orders__line_items__tax_lines
      - name: products__variants
      - name: products__options
      - name: products__options__values
      - name: products__images
      - name: products__images__variant_ids
      - name: products__image__variant_ids
  - name: transformed_data
    schema: '{{ var ("destination_dataset_name") }}'
    tables:
      - name: dlt_processed_load_ids

models:
      - name: dlt_processed_load_ids
        description: "This table contains all processed load ids for incremental loading"
      - name: _dlt_loads
        description: "Created by DLT. Tracks completed loads"
        columns:
          - name: load_id
            tests:
              - not_null
          - name: schema_name
          - name: status
            tests:
              - not_null
          - name: inserted_at
            tests:
              - not_null
          - name: schema_version_hash
      - name: products
        columns:
          - name: id
            tests:
              - not_null
          - name: title
          - name: vendor
          - name: product_type
          - name: created_at
          - name: handle
          - name: updated_at
          - name: published_scope
          - name: tags
          - name: status
          - name: admin_graphql_api_id
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
          - name: image__id
          - name: image__alt
          - name: image__position
          - name: image__product_id
          - name: image__created_at
          - name: image__updated_at
          - name: image__admin_graphql_api_id
          - name: image__width
          - name: image__height
          - name: image__src
          - name: published_at
          - name: body_html
      - name: orders
        columns:
          - name: id
            tests:
              - not_null
          - name: admin_graphql_api_id
          - name: app_id
          - name: browser_ip
          - name: buyer_accepts_marketing
          - name: checkout_id
          - name: checkout_token
          - name: client_details__browser_ip
          - name: client_details__user_agent
          - name: closed_at
          - name: confirmation_number
          - name: confirmed
          - name: created_at
          - name: currency
          - name: current_subtotal_price
          - name: current_subtotal_price_set__shop_money__amount
          - name: current_subtotal_price_set__shop_money__currency_code
          - name: current_subtotal_price_set__presentment_money__amount
          - name: current_subtotal_price_set__presentment_money__currency_code
          - name: current_total_discounts
          - name: current_total_discounts_set__shop_money__amount
          - name: current_total_discounts_set__shop_money__currency_code
          - name: current_total_discounts_set__presentment_money__amount
          - name: current_total_discounts_set__presentment_money__currency_code
          - name: current_total_price
          - name: current_total_price_set__shop_money__amount
          - name: current_total_price_set__shop_money__currency_code
          - name: current_total_price_set__presentment_money__amount
          - name: current_total_price_set__presentment_money__currency_code
          - name: current_total_tax
          - name: current_total_tax_set__shop_money__amount
          - name: current_total_tax_set__shop_money__currency_code
          - name: current_total_tax_set__presentment_money__amount
          - name: current_total_tax_set__presentment_money__currency_code
          - name: customer_locale
          - name: email
          - name: estimated_taxes
          - name: financial_status
          - name: fulfillment_status
          - name: location_id
          - name: name
          - name: number
          - name: order_number
          - name: order_status_url
          - name: presentment_currency
          - name: processed_at
          - name: reference
          - name: source_identifier
          - name: source_name
          - name: subtotal_price
          - name: subtotal_price_set__shop_money__amount
          - name: subtotal_price_set__shop_money__currency_code
          - name: subtotal_price_set__presentment_money__amount
          - name: subtotal_price_set__presentment_money__currency_code
          - name: tags
          - name: tax_exempt
          - name: taxes_included
          - name: test
          - name: token
          - name: total_discounts
          - name: total_discounts_set__shop_money__amount
          - name: total_discounts_set__shop_money__currency_code
          - name: total_discounts_set__presentment_money__amount
          - name: total_discounts_set__presentment_money__currency_code
          - name: total_line_items_price
          - name: total_line_items_price_set__shop_money__amount
          - name: total_line_items_price_set__shop_money__currency_code
          - name: total_line_items_price_set__presentment_money__amount
          - name: total_line_items_price_set__presentment_money__currency_code
          - name: total_outstanding
          - name: total_price
          - name: total_price_set__shop_money__amount
          - name: total_price_set__shop_money__currency_code
          - name: total_price_set__presentment_money__amount
          - name: total_price_set__presentment_money__currency_code
          - name: total_shipping_price_set__shop_money__amount
          - name: total_shipping_price_set__shop_money__currency_code
          - name: total_shipping_price_set__presentment_money__amount
          - name: total_shipping_price_set__presentment_money__currency_code
          - name: total_tax
          - name: total_tax_set__shop_money__amount
          - name: total_tax_set__shop_money__currency_code
          - name: total_tax_set__presentment_money__amount
          - name: total_tax_set__presentment_money__currency_code
          - name: total_tip_received
          - name: total_weight
          - name: updated_at
          - name: user_id
          - name: billing_address__first_name
          - name: billing_address__address1
          - name: billing_address__city
          - name: billing_address__zip
          - name: billing_address__province
          - name: billing_address__country
          - name: billing_address__last_name
          - name: billing_address__address2
          - name: billing_address__latitude
          - name: billing_address__longitude
          - name: billing_address__name
          - name: billing_address__country_code
          - name: billing_address__province_code
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: customers
        columns:
          - name: id
            tests:
              - not_null
          - name: email
          - name: created_at
          - name: updated_at
          - name: first_name
          - name: last_name
          - name: orders_count
          - name: state
          - name: total_spent
          - name: verified_email
          - name: tax_exempt
          - name: tags
          - name: currency
          - name: phone
          - name: accepts_marketing
          - name: marketing_opt_in_level
          - name: email_marketing_consent__state
          - name: email_marketing_consent__opt_in_level
          - name: sms_marketing_consent__state
          - name: sms_marketing_consent__opt_in_level
          - name: sms_marketing_consent__consent_collected_from
          - name: admin_graphql_api_id
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
          - name: note
          - name: default_address__id
          - name: default_address__customer_id
          - name: default_address__first_name
          - name: default_address__last_name
          - name: default_address__company
          - name: default_address__address1
          - name: default_address__city
          - name: default_address__country
          - name: default_address__zip
          - name: default_address__name
          - name: default_address__country_code
          - name: default_address__country_name
          - name: default_address__default
      - name: customers__addresses
        columns:
          - name: id
          - name: customer_id
          - name: first_name
          - name: last_name
          - name: company
          - name: address1
          - name: city
          - name: country
          - name: zip
          - name: name
          - name: country_code
          - name: country_name
          - name: default
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: orders__payment_gateway_names
        columns:
          - name: value
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: orders__tax_lines
        columns:
          - name: price
          - name: rate
          - name: title
          - name: price_set__shop_money__amount
          - name: price_set__shop_money__currency_code
          - name: price_set__presentment_money__amount
          - name: price_set__presentment_money__currency_code
          - name: channel_liable
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: orders__fulfillments
        columns:
          - name: id
          - name: admin_graphql_api_id
          - name: created_at
          - name: location_id
          - name: name
          - name: order_id
          - name: service
          - name: status
          - name: updated_at
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: orders__fulfillments__line_items
        columns:
          - name: id
          - name: admin_graphql_api_id
          - name: fulfillable_quantity
          - name: fulfillment_service
          - name: fulfillment_status
          - name: gift_card
          - name: grams
          - name: name
          - name: price
          - name: price_set__shop_money__amount
          - name: price_set__shop_money__currency_code
          - name: price_set__presentment_money__amount
          - name: price_set__presentment_money__currency_code
          - name: product_exists
          - name: product_id
          - name: quantity
          - name: requires_shipping
          - name: sku
          - name: taxable
          - name: title
          - name: total_discount
          - name: total_discount_set__shop_money__amount
          - name: total_discount_set__shop_money__currency_code
          - name: total_discount_set__presentment_money__amount
          - name: total_discount_set__presentment_money__currency_code
          - name: variant_id
          - name: variant_inventory_management
          - name: vendor
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
          - name: variant_title
      - name: orders__fulfillments__line_items__tax_lines
        columns:
          - name: channel_liable
          - name: price
          - name: price_set__shop_money__amount
          - name: price_set__shop_money__currency_code
          - name: price_set__presentment_money__amount
          - name: price_set__presentment_money__currency_code
          - name: rate
          - name: title
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: orders__fulfillments__receipt__gift_cards
        columns:
          - name: id
          - name: line_item_id
          - name: masked_code
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: orders__line_items
        columns:
          - name: id
          - name: admin_graphql_api_id
          - name: fulfillable_quantity
          - name: fulfillment_service
          - name: fulfillment_status
          - name: gift_card
          - name: grams
          - name: name
          - name: price
          - name: price_set__shop_money__amount
          - name: price_set__shop_money__currency_code
          - name: price_set__presentment_money__amount
          - name: price_set__presentment_money__currency_code
          - name: product_exists
          - name: product_id
          - name: quantity
          - name: requires_shipping
          - name: sku
          - name: taxable
          - name: title
          - name: total_discount
          - name: total_discount_set__shop_money__amount
          - name: total_discount_set__shop_money__currency_code
          - name: total_discount_set__presentment_money__amount
          - name: total_discount_set__presentment_money__currency_code
          - name: variant_id
          - name: variant_title
          - name: vendor
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
          - name: variant_inventory_management
      - name: orders__line_items__tax_lines
        columns:
          - name: channel_liable
          - name: price
          - name: price_set__shop_money__amount
          - name: price_set__shop_money__currency_code
          - name: price_set__presentment_money__amount
          - name: price_set__presentment_money__currency_code
          - name: rate
          - name: title
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: products__variants
        columns:
          - name: id
            tests:
              - unique
          - name: product_id
          - name: title
          - name: price
          - name: position
          - name: inventory_policy
          - name: option1
          - name: created_at
          - name: updated_at
          - name: taxable
          - name: fulfillment_service
          - name: grams
          - name: inventory_management
          - name: requires_shipping
          - name: sku
          - name: weight
          - name: weight_unit
          - name: inventory_item_id
          - name: inventory_quantity
          - name: old_inventory_quantity
          - name: admin_graphql_api_id
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
          - name: image_id
          - name: compare_at_price
      - name: products__options
        columns:
          - name: id
          - name: product_id
          - name: name
          - name: position
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: products__options__values
        columns:
          - name: value
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: products__images
        columns:
          - name: id
          - name: alt
          - name: position
          - name: product_id
          - name: created_at
          - name: updated_at
          - name: admin_graphql_api_id
          - name: width
          - name: height
          - name: src
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: products__images__variant_ids
        columns:
          - name: value
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: products__image__variant_ids
        columns:
          - name: value
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique