version: 2
sources:
  - name: raw_data
    schema: '{{ var ("source_dataset_name") }}'
    tables:
      - name: _dlt_loads
  - name: transformed_data
    schema: '{{ var ("destination_dataset_name") }}'
    tables:
      - name: dlt_processed_load_ids

models:
      - name: dlt_processed_load_ids
        description: "This table contains all processed load ids for incremental loading"
      - name: _dlt_loads
        description: "Created by DLT. Tracks completed loads"
        columns:
          - name: load_id
            tests:
              - not_null
          - name: schema_name
          - name: status
            tests:
              - not_null
          - name: inserted_at
            tests:
              - not_null
          - name: schema_version_hash